### ISSUE TITLE
Licensing information is confusing

### ISSUE THREAD

**Issue by kwavnet** [avnet-iotconnect/iotc-c-lib#18]
https://github.com/avnet-iotconnect/iotc-c-lib/blob/f321b962bccbaea4c8cb99625781ffe2997e8cd9/src/iotconnect_discovery.c#L3 and many many more across *ALL* of the public repositories of this organization contain that referenced line in various file headers.

I'm confused: how can it be confidential if anyone can see it here on github?

Also `Unauthorized copying of this file, via any medium is strictly prohibited` is a catch22 in itself, if I would clone the public repository, I would be immediately violating this clause.

In general I'm entirely missing any kind of licensing information in the organization's repositories.

**Comment by nik-markovic** [comment]
Hi @kwavnet,

I am sorry about our lack of clarity on the issue. You brought up a very valid point as I haven't gotten a chance to check back with the legal team about what specific license we want to apply. So I just left is as *Copyright Avnet* to be safe.

I probably didn't mean to leave the "Unauthorized copying of this file, via any medium is strictly prohibited" part in the code and I will remove it.

In the meanwhile, feel free to use the code however you see fit for the purpse of connecting your device to IoTConnect.

If you have any other concerns feel free to email me at Nikola.Markovic@avnet.com.

Thanks!
Nik

**Comment by nik-markovic** [comment]
The license is now clearly stated as MIT. Thanks for pointing this out.
